services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: my_db_container   # Задаем имя контейнера
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin12345
      POSTGRES_DB: myappdatabase_new
    ports:
      - "5432:8080"